# Generated by Django 5.2.1 on 2025-05-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacksetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbacktransaction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
