# Generated by Django 5.2.1 on 2025-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_cashbacksetting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacktransaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
